### ISSUE TITLE
表紙のmargin指定について、記述を変更する

### ISSUE THREAD

**Issue by try0** [try0/mkdocs-example#2]
内部要素にマイナスのマージンじゃなく、ページのマージンを変更するよう記述する
```css
@page :first {
    margin: 0px;
}
```
